version: "3"

volumes:
  media_vol:
  static_vol:

networks:
  nginx_network:
    driver: bridge

services:
  web:
    build: ./dj_test
    expose:
      - "8000"
    volumes:
      - ./dj_test:/var/www/html/dj_test
      - static_vol:/var/www/html/dj_test/static
      - media_vol:/var/www/html/dj_test/media
      - ./compose/uwsgi:/tmp
    networks:
      - nginx_network
    restart: always
    tty: true
    stdin_open: true
  
  nginx:
    build: ./compose/nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./compose/nginx/log:/var/log/nginx
      - static_vol:/usr/share/nginx/html/static
      - media_vol:/usr/share/nginx/html/media
    networks:
      - nginx_network
    depends_on:
      - web
    restart: always

